### ISSUE TITLE
Incorporate API call to update version of image in UConn cluster

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/Biosimulations_COMBINE_archive_test_suite#17]

**Comment by bilalshaikh42** [comment]
The images of the HPC can be updated by making a post request to the /images/refresh endpoint on the dispatch api.

The body of the request should contain a json object, with the "simulator" and "version" fields set to the image that needs to be refreshed. 

Documentation for the endpoint is [here](https://run.api.biosimulations.dev/#/Images/ImagesController_refreshImage)

The endpoint requires authentication via JWT using the same client_id and client_secret as uploading simulators. However, in the authentication flow, the audience field should be set to "dispatch.biosimulations.org" rather than "api.biosimulators.org".

**Comment by jonrkarr** [comment]
Example payload
```json
{
  "simulator": "copasi",
  "version": "4.30.233"
}
```

**Comment by jonrkarr** [comment]
I added a call to the the dispatch API.

Todo
- [x] Deploy: @bilalshaikh42 is this ready to deploy (using https://run.api.biosimulations.dev/)?
- [x] Change dispatch endpoint to production server (https://run.api.biosimulations.org/)

**Comment by bilalshaikh42** [comment]
Yes, the endpoint is working on run.api.biosimulations.dev. It can be updated to the org domain later, but these both will have the same effect as the image cache is shared

**Comment by jonrkarr** [comment]
This is deployed. The GitHub actions that review simulators will now trigger this endpoint.

I'll leave the issue open to remind us to update the endpoint to `.org`.

**Comment by jonrkarr** [comment]
@bilalshaikh42 FYI, I needed to grant the "GitHub Simulators Actions" Auth0 application access to the Auth0 "Dispatch API" (`dispatch.biosimulations.org`) with permissions `refresh:Images`.

I ran the workflow -- including triggering the refreshing of the images -- for all 9 simulation tools.

**Comment by bilalshaikh42** [comment]
Yes, sorry. I thought I had already granted the permissions.

**Comment by jonrkarr** [comment]
Done.
