### ISSUE TITLE
Test suite documentation

### ISSUE THREAD

**Issue by gmarupilla** [reproducible-biomedical-modeling/Biosimulations_COMBINE_archive_test_suite#28]
Hello @jonrkarr,

Is there any kind of doc related to biosimulators_test_suite which can tell which test is shown in GH action logs checks for exactly what thing? Because it's not very much intuitive from the Test names themselves.

I tried looking into code for few minutes, but to map out the complete functioning of the code, I'd have to spend a lot of time because of the high level of inheritance among the classes, which would be even more for all the tests cases.

It'll help a great deal if we have a written test that checks for what (possibly with examples).

**Comment by jonrkarr** [comment]
The tests are basically just checking that the expected reports are created with the expected data sets and time points (i.e., the tests each use very similar assertions). 

The main difference between the tests are what reports, data sets, and time points are expected. The tests generate tasks, reports, and data sets in order to check support for specific features of SED-ML. The feature check by each test is indicated by the name of the test and the doc string, which gets compiled into the test report. The names and description should be self-explanatory for someone familiar with SED-ML.

As I mentioned by email, we could save the synthetically generated COMBINE archives so that you can inspect them and run them directly with VCell.

**Comment by jonrkarr** [comment]
I added an option to the command-line program to save the COMBINE archives generated by the tests to a directory. This will enable you to see how test test suite is checking for support for various features of SED-ML and COMBINE. This will also indicate (a) the order in which the test suite executes the archives and (b) whether simulators are expected to successfully execute each archive, or whether the execution of each archive should fail.

The command-line program can be installed from PyPI or this repository.

Here's instructions in the documentation:
https://biosimulators.github.io/Biosimulators_test_suite/tutorial.html#running-the-test-suite-locally
